"""Site Records PDF generation.

This needs to read as a formal document — cover page, clearly headed
sections, a footer on every page — not a screenshot of the app. Deliberately
plain: black text on white, a conservative serif, hairline rules. A legal or
insurance document should read as credible on its own terms, not carry the
dark ops-terminal branding the rest of the app uses.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (PageBreak, Paragraph, SimpleDocTemplate, Spacer,
                                Table, TableStyle)

from .schemas import RecordExportRequest, SiteRecordsOut

SECTION_TITLES = {
    "shifts": "Coverage & Shifts",
    "check_ins": "Check-In Records",
    "invoices": "Financial Summary",
    "incidents": "Incidents & SOS",
    "compliance": "Compliance",
}

_styles = getSampleStyleSheet()
_title_style = ParagraphStyle("DocTitle", parent=_styles["Title"], fontName="Times-Bold", fontSize=22, spaceAfter=6)
_h1 = ParagraphStyle("SectionHead", parent=_styles["Heading1"], fontName="Times-Bold", fontSize=14,
                     spaceBefore=18, spaceAfter=8, textColor=colors.HexColor("#1a1a1a"))
_body = ParagraphStyle("Body", parent=_styles["Normal"], fontName="Times-Roman", fontSize=10, leading=14)
_meta = ParagraphStyle("Meta", parent=_styles["Normal"], fontName="Helvetica", fontSize=9,
                       textColor=colors.HexColor("#444444"), leading=13)
_empty = ParagraphStyle("Empty", parent=_body, textColor=colors.HexColor("#777777"), fontName="Times-Italic")

TABLE_HEADER_BG = colors.HexColor("#e8e8e8")
RULE_COLOR = colors.HexColor("#999999")


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#666666"))
    canvas.drawString(0.75 * inch, 0.5 * inch,
                      f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} — "
                      f"system-generated record from Blackstone Security operations data")
    canvas.drawRightString(LETTER[0] - 0.75 * inch, 0.5 * inch, f"Page {doc.page}")
    canvas.restoreState()


def _table(headers: list[str], rows: list[list[str]]) -> Table:
    data = [headers] + rows
    t = Table(data, repeatRows=1, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_BG),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("LINEBELOW", (0, 0), (-1, 0), 0.75, colors.black),
        ("LINEBELOW", (0, 1), (-1, -1), 0.25, RULE_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


def build_pdf(records: SiteRecordsOut, request: RecordExportRequest, generated_by_name: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            topMargin=0.85 * inch, bottomMargin=0.85 * inch,
                            leftMargin=0.75 * inch, rightMargin=0.75 * inch)
    story = []

    # ── Cover ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.2 * inch))
    story.append(Paragraph("Site Records", _title_style))
    story.append(Paragraph(records.site_name, ParagraphStyle(
        "Sub", parent=_styles["Normal"], fontName="Times-Roman", fontSize=15, spaceAfter=28)))

    def _fmt(d):
        return f"{d.strftime('%B')} {d.day}, {d.strftime('%Y')}"
    period = f"{_fmt(records.period_start)} — {_fmt(records.period_end)}"
    cover_rows = [
        ["Period covered", period],
        ["Generated", f"{datetime.utcnow().strftime('%B')} {datetime.utcnow().day}, {datetime.utcnow().strftime('%Y at %H:%M UTC')}"],
        ["Generated by", generated_by_name],
        ["Sections included", ", ".join(SECTION_TITLES.get(s, s) for s in request.sections)],
        ["Financial detail", "Included" if request.include_rates else "Excluded (rate figures withheld)"],
    ]
    if request.purpose:
        cover_rows.append(["Stated purpose", request.purpose])
    cover_table = Table([[Paragraph(f"<b>{k}</b>", _meta), Paragraph(v, _meta)] for k, v in cover_rows],
                        colWidths=[1.6 * inch, 4.4 * inch])
    cover_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(
        "This document is generated from Blackstone Security operations records. It is a point-in-time "
        "export: the underlying data may be corrected or updated after generation, but this record is not "
        "regenerated to reflect such changes. A new export must be produced to capture current data.",
        _meta))
    story.append(PageBreak())

    for section in request.sections:
        if section == "shifts":
            _shifts_section(story, records)
        elif section == "check_ins":
            _checkins_section(story, records)
        elif section == "invoices":
            _invoices_section(story, records, request.include_rates)
        elif section == "incidents":
            _incidents_section(story, records)
        elif section == "compliance":
            _compliance_section(story, records)

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _shifts_section(story, records: SiteRecordsOut):
    story.append(Paragraph("Coverage &amp; Shifts", _h1))
    if not records.shifts:
        story.append(Paragraph("No approved shifts in this period.", _empty))
        return
    rows = []
    for s in records.shifts:
        names = ", ".join(a.operator_name or "Open" for a in s.assignments) or "—"
        rows.append([s.date.isoformat(), s.shift_name, f"{s.slots_filled}/{s.slots_total}", names])
    story.append(_table(["Date", "Shift", "Filled", "Operators"], rows))


def _checkins_section(story, records: SiteRecordsOut):
    story.append(Paragraph("Check-In Records", _h1))
    if not records.check_ins:
        story.append(Paragraph("No check-in records in this period.", _empty))
        return
    rows = []
    for c in records.check_ins:
        actual_in = c.actual_check_in.strftime("%H:%M") if c.actual_check_in else "—"
        actual_out = c.actual_check_out.strftime("%H:%M") if c.actual_check_out else "—"
        late = []
        if c.late_in_minutes:
            late.append(f"{c.late_in_minutes}m late in")
        if c.late_out_minutes:
            late.append(f"{c.late_out_minutes}m late out")
        rows.append([
            c.date.isoformat(), c.operator_name, c.shift_name,
            f"{c.scheduled_start.strftime('%H:%M')}-{c.scheduled_end.strftime('%H:%M')}",
            f"{actual_in} / {actual_out}",
            "Not captured",
            ", ".join(late) if late else "—",
        ])
    story.append(_table(
        ["Date", "Operator", "Shift", "Scheduled", "Actual in/out", "Location", "Notes"], rows))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "“Location: Not captured” reflects that this deployment does not currently record "
        "check-in location — this is a statement of what the system captured, not an assertion about "
        "where the operator was.", _meta))


def _invoices_section(story, records: SiteRecordsOut, include_rates: bool):
    story.append(Paragraph("Financial Summary", _h1))
    if not records.invoices:
        story.append(Paragraph("No invoiced hours for this site in this period.", _empty))
        return
    if include_rates:
        rows = [[i.operator_name, f"{i.period_month:02d}/{i.period_year}", i.status.value.title(),
                f"{i.site_hours:.2f}", f"${i.site_amount:.2f}" if i.site_amount is not None else "—"]
                for i in records.invoices]
        story.append(_table(["Operator", "Period", "Status", "Hours (this site)", "Amount (this site)"], rows))
    else:
        rows = [[i.operator_name, f"{i.period_month:02d}/{i.period_year}", i.status.value.title(),
                f"{i.site_hours:.2f}"] for i in records.invoices]
        story.append(_table(["Operator", "Period", "Status", "Hours (this site)"], rows))
        story.append(Spacer(1, 6))
        story.append(Paragraph("Rate and amount figures were excluded from this export by choice at generation time.", _meta))


def _incidents_section(story, records: SiteRecordsOut):
    story.append(Paragraph("Incidents &amp; SOS", _h1))
    if not records.incidents:
        story.append(Paragraph("No incident or SOS activity recorded for this site in this period.", _empty))
        return
    rows = [[i.date.isoformat(), i.incident_type, i.operator_name or "—", i.summary]
           for i in records.incidents]
    story.append(_table(["Date", "Type", "Operator", "Summary"], rows))


def _compliance_section(story, records: SiteRecordsOut):
    story.append(Paragraph("Compliance", _h1))
    if not records.compliance:
        story.append(Paragraph("No operators with assignments in this period.", _empty))
        return
    rows = [[c.operator_name, c.licence_status.value.replace("_", " ").title(),
            c.licence_expiry.isoformat() if c.licence_expiry else "—"]
           for c in records.compliance]
    story.append(_table(["Operator", "Licence status", "Licence expiry"], rows))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Licence status reflects current records as of the time this document was generated, "
        "not necessarily status as of the period covered above.", _meta))
